name: briscola
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.32.0
  flutter_blue_plus: ^2.0.2
  bluetooth_low_energy: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/baton.png
    - assets/images/coin.png
    - assets/images/cup.png
    - assets/images/sword.png
    - assets/images/jack.png
    - assets/images/knight.png
    - assets/images/king.png
